apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.app.containerPort }}
    targetPort: {{ .Values.app.containerPort }}
