apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: irgashevsardor/tasks-app
        ports:
        - containerPort: {{ .Values.app.containerPort }}
        env:
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.app.name }}-configmap
                key: mysql_user
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.app.name }}-configmap
                key: mysql_host
          - name: MYSQL_PASSWORD
            value: "4697"
          - name: MYSQL_DB
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.app.name }}-configmap
                key: mysql_db
        volumeMounts:
         - name: config
           mountPath: "/config"
           readOnly: true

      volumes:
        - name: config
          configMap:
            name: app-configmap