apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Values.db.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.name }}
    spec:
      volumes:
      - name: {{ .Values.db.name }}-storage
        persistentVolumeClaim:
          claimName: {{ .Values.db.name }}-pvc
      containers:
      - name: {{ .Values.db.name }}
        image: mysql:8.0
        ports:
        - containerPort: {{ .Values.db.containerPort }}
        volumeMounts:
          - name: {{ .Values.db.name }}-storage
            mountPath: {{ .Values.db.mountPath }}
            subPath: {{ .Values.db.subPath }}
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.app.name}}-secret
                key: mysql_root_psswd
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.app.name }}-configmap
                key: mysql_user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.app.name }}-secret
                key: mysql_user_psswd
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.app.name }}-configmap
                key: mysql_db