apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.db.name }} 
  ports:
  - protocol: TCP
    port: {{ .Values.db.containerPort }}
    targetPort: {{ .Values.db.containerPort }}
