apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Values.db.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.name }}
    spec:
      volumes:
      - name: {{ .Values.db.name }}-storage
        persistentVolumeClaim:
          claimName: {{ .Values.db.name }}-pvc
      containers:
      - name: {{ .Values.db.name }}
        image: mysql:8.0
        ports:
        - containerPort: {{ .Values.db.containerPort }}
        volumeMounts:
          - name: {{ .Values.db.name }}-storage
            mountPath: {{ .Values.db.mountPath }}
            subPath: {{ .Values.db.subPath }}
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-env-data
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-env-data
                key: MYSQL_PASSWORD
          - name: MYSQL_USER
            value: "user"
          - name: MYSQL_DATABASE
            value: "list"
